#!/bin/sh

# Here goes:
# - path variables
# - local aliases

################################################
##                 ALIASES                    ##
################################################

alias doco='docker-compose'
alias doma='docker-machine'
alias emacs="cowthink Noonononono. Nope."
alias gpg="gpg2"
alias i=ionic
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias jk="cowsay -e ^^ -T U Just Kiddin\'"
alias stripcolors='gsed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"'
alias tks="tmux kill-session"
alias trash=rmtrash

# Some aliases to make my bbb life easier
alias bbbkom='open "/Users/nicolai/Dropbox/BBB Komp"'
alias bbbsax='open "/Users/nicolai/Dropbox/BBB Sax/Dansemappe-sax"'
alias bbbtru='open "/Users/nicolai/Dropbox/BBB Trumpet/Dansemappe-trompet"'
alias bbbtro='open "/Users/nicolai/Dropbox/BBB Trombone/Dansemappe-trombone"'
alias bbbvoc='open "/Users/nicolai/Dropbox/BBB Vokal/Dansemappe - Vokal"'

# It's effing impossible to know what tags are available
# on container images hosted on gcr.io, so here's an alias
gcr() {
  curl -k -s -X GET "https://gcr.io/v2/google_containers/$1/tags/list" \
  | jq -r '.tags[]'
}

# Elimd server
alias eclimd="/Applications/Eclipse.app/Contents/Eclipse/eclimd"

# GUI for automata
JFLAP_PATH="/Users/nicolai/Downloads/JFLAP.jar"
# shellcheck disable=SC2139
alias jflap="java -jar $JFLAP_PATH"

################################################
##                  CONFIG                    ##
################################################

export PATH

# Brew
if command -v brew >/dev/null 2>&1 ; then
    ## Brew completion
    source /usr/local/etc/bash_completion.d/*
    ## To use GNU-utilities
    PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
    MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"
    PATH="$(brew --prefix)/sbin:$PATH"
fi

# Completion scripts which doesn't have anywhere else to live
if [ -d "$HOME/completion/" ]
then
    source "$HOME"/completion/*
fi

# Dinghy
export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_CERT_PATH=/Users/nicolai/.docker/machine/machines/dinghy
export DOCKER_TLS_VERIFY=1
export DOCKER_MACHINE_NAME=dinghy

# FZF
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

#Git stuff
export GIT_PROMPT_ONLY_IN_REPO=1
#GIT_PROMPT_SHOW_LAST_COMMAND_INDICATOR=1

# OSX
# Decrease animation duration when using expose
wanted_duration="0.2"
current_duration="$(defaults read com.apple.dock expose-animation-duration)"

if [ "$current_duration" != "$wanted_duration" ] ; then
    defaults write com.apple.dock expose-animation-duration -float 0.2; killall Dock
fi


################################################
##                  PATHS                     ##
################################################

# Android SDK
export ANDROID_HOME=$HOME/Library/Android/sdk
PATH=$PATH:$ANDROID_HOME/tools
PATH=$PATH:$ANDROID_HOME/platform-tools


AUTOENV_PATH="/usr/local/opt/autoenv/activate.sh"
test -f "$AUTOENV_PATH" && source "$AUTOENV_PATH"

# Findbugs
export FINDBUGS_HOME=/usr/local/Cellar/findbugs/3.0.1/libexec

# Go
export GOPATH=$HOME/go
# export GOROOT=/usr/local/go
# PATH=$PATH:$GOPATH/bin:$GOROOT/bin
PATH=$PATH:$GOPATH/bin
PATH=$PATH:/usr/local/opt/go/libexec/bin

# Haskell
CABALPATH="$HOME/.cabal"
PATH=$PATH:$CABALPATH/bin

# Java
export JUNIT_HOME="$HOME/java"
PATH="$PATH:$JUNIT_HOME"
export CLASSPATH="$CLASSPATH:$JUNIT_HOME/junit-4.12.jar:$JUNIT_HOME/hamcrest-core-1.3.jar"

# PHP
PATH="$HOME/.composer/vendor/bin:$PATH"

# openvpn
PATH="$PATH:/usr/local/Cellar/openvpn/2.3.6/sbin"

# quicklook
ql() {
  qlmanage -p "$1" 1>2 2>/dev/null
}

# m-cli: https://github.com/rgcr/m-cli
PATH="$PATH:/usr/local/m-cli"

# PERL
PATH="/Users/nicolai/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/Users/nicolai/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/nicolai/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT='--install_base "/Users/nicolai/perl5"';
export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/nicolai/perl5";
export PERL_MM_OPT;
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"

# RUST
PATH="$HOME/.cargo/bin:$PATH"


################################################
##            OWN BINARIES AND STUFF          ##
################################################

# Have this last to make sure my own bins are searched first
PATH="$HOME/bin::$PATH"
# PATH="$HOME/bin/git-radar:$PATH"


# # shellcheck disable=SC1091
# # shellcheck source=/Users/nicolai/bin/getKeyboardLayout.sh
# source "$HOME/bin/getKeyboardLayout.sh"
